###
POST http://127.0.0.1:8080/networks/ip_trans
Content-Type: application/json

{
    "trans_ori":"asdasd叔叔叔叔叔叔叔叔叔叔说"
}
###
POST http://127.0.0.1:8080/networks/ip_trans
Content-Type: application/json

{
  "trans_ori":"0x0103FFA4"
}
###
POST http://127.0.0.1:8080/networks/ip_trans
Content-Type: application/json

{
  "trans_ori":"0x0a103FFA"
}
###
GET http://127.0.0.1:8080/api/supports

